name: iq_offers
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get:
  lottie:
  http:
  firebase_core:
  firebase_messaging:
  flutter_launcher_icons: ^0.13.1
  cached_network_image:
  dependency_validator: ^3.2.2
  change_app_package_name: ^1.1.0
  icons_plus: ^5.0.0
  flutter_cached_manager:
  video_player:
  chewie: ^1.7.4
  get_storage:
  card_swiper:
  awesome_notifications:
  firebase_crashlytics: ^3.4.8
  easy_splash_screen:
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.1
  auto_size_text: ^3.0.0
  flutter_blurhash: ^0.8.2
  flutter_expandable_fab: ^2.0.0
  url_launcher: ^6.2.2
  vector_math:
  flutter_rating_bar: ^4.0.1
  timer_builder: ^2.0.0
  animated_number: ^1.0.2
  coupon_uikit: ^0.2.0
  jiffy:
  encrypt: ^5.0.2
  pretty_qr_code: ^3.0.0
  story_view: ^0.16.0
  dotted_decoration: ^2.0.0
  elevarm_ui: ^0.9.4
  pie_chart: ^5.4.0
  ai_barcode_scanner: ^3.4.1
  auto_size_text_field: ^2.2.2
  image_picker:




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/offers_empty.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  dart_code_metrics: ^5.7.6
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria/Alexandria-Bold.ttf
          weight: 700



  assets:
    - assets/lottie/
    - assets/images/
    - assets/
    - assets/fonts/
    - assets/fonts/Alexandria/
    - .env